--------------------------------------------------------
--  파일이 생성됨 - 목요일-8월-06-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EN_BOARD
--------------------------------------------------------

  CREATE TABLE "PROENG"."EN_BOARD" 
   (	"CODE_NO" VARCHAR2(10 BYTE), 
	"SEQ_NO" NUMBER(10,0), 
	"ID" VARCHAR2(30 BYTE), 
	"BOARD_TITLE" VARCHAR2(4000 BYTE), 
	"BOARD_CONTENT" VARCHAR2(4000 BYTE), 
	"BOARD_GROUP" NUMBER(10,0), 
	"BOARD_DEPTH" NUMBER(3,0), 
	"BOARD_HIT" NUMBER(10,0), 
	"BOARD_CRE_DATE" DATE, 
	"BOARD_MOD_DATE" DATE, 
	"IS_ATCH_FILE" VARCHAR2(1 BYTE), 
	"IS_DELETE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "PROENG"."EN_BOARD"."CODE_NO" IS '코드번호';
   COMMENT ON COLUMN "PROENG"."EN_BOARD"."SEQ_NO" IS '문제번호';
   COMMENT ON COLUMN "PROENG"."EN_BOARD"."ID" IS '작성자';
   COMMENT ON COLUMN "PROENG"."EN_BOARD"."BOARD_TITLE" IS '게시글 제목 ( 문제 )';
   COMMENT ON COLUMN "PROENG"."EN_BOARD"."BOARD_CONTENT" IS '게시글 내용';
   COMMENT ON COLUMN "PROENG"."EN_BOARD"."BOARD_GROUP" IS '게시글 원글 식별자';
   COMMENT ON COLUMN "PROENG"."EN_BOARD"."BOARD_DEPTH" IS '게시글 답글 계층';
   COMMENT ON COLUMN "PROENG"."EN_BOARD"."BOARD_HIT" IS '게시글 조회수';
   COMMENT ON COLUMN "PROENG"."EN_BOARD"."BOARD_CRE_DATE" IS '게시글 작성일';
   COMMENT ON COLUMN "PROENG"."EN_BOARD"."BOARD_MOD_DATE" IS '게시글 최종 수정일';
   COMMENT ON COLUMN "PROENG"."EN_BOARD"."IS_ATCH_FILE" IS '첨부파일 여부';
   COMMENT ON COLUMN "PROENG"."EN_BOARD"."IS_DELETE" IS '게시글 삭제여부';
   COMMENT ON TABLE "PROENG"."EN_BOARD"  IS '게시판';
REM INSERTING into PROENG.EN_BOARD
SET DEFINE OFF;
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('102',1,'5','1',null,0,0,1,to_date('15/07/24','RR/MM/DD'),to_date('15/07/24','RR/MM/DD'),null,'N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('102',2,'5','1',null,0,0,0,to_date('15/07/24','RR/MM/DD'),to_date('15/07/24','RR/MM/DD'),null,'N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('102',3,'5','1',null,0,0,0,to_date('15/07/24','RR/MM/DD'),to_date('15/07/24','RR/MM/DD'),null,'N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',4,'5','eqrar','rtewwt',null,null,1,to_date('15/07/28','RR/MM/DD'),null,null,'N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',5,'5','TESET','TESTE',null,null,0,to_date('15/07/28','RR/MM/DD'),null,null,'Y');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',6,'5','RWWTR','FGFSDGFSG',null,null,0,to_date('15/07/28','RR/MM/DD'),null,null,'N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',7,'5','DFGFFS','FAFGFD',null,null,0,to_date('15/07/28','RR/MM/DD'),null,null,'Y');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',8,'5','FGFGFSDG','ZDFG',null,null,0,to_date('15/07/28','RR/MM/DD'),null,null,'Y');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',9,'5','DAFD','DASFD',null,null,0,to_date('15/07/28','RR/MM/DD'),null,null,'Y');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',10,'5','testeate','fgffgfg',null,null,1,to_date('15/07/28','RR/MM/DD'),null,null,'Y');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',11,'5','gdag','gdfgs',null,null,0,to_date('15/07/28','RR/MM/DD'),null,null,'Y');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',12,'5','wxded','edcedc',null,null,0,to_date('15/07/28','RR/MM/DD'),null,null,'Y');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',13,'5','gggffg','fgf',null,null,0,to_date('15/07/28','RR/MM/DD'),null,null,null);
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',14,'5','ffgfg','vcvxbvxb',null,null,0,to_date('15/07/28','RR/MM/DD'),null,null,null);
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',15,'5','rfgfggs','fs',null,null,0,to_date('15/07/28','RR/MM/DD'),null,null,null);
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',16,'5','gfgfg','dfdfdf',null,null,0,to_date('15/07/28','RR/MM/DD'),null,null,'Y');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',17,'1','ddfsdf','dfsdf',null,null,1,to_date('15/07/28','RR/MM/DD'),null,null,'Y');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('104',18,'1','5555555555','555555555555',null,null,1,to_date('15/07/28','RR/MM/DD'),null,null,null);
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('102',19,'1','test',null,0,0,2,to_date('15/07/29','RR/MM/DD'),to_date('15/07/29','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',20,'1','No pain No gain',null,0,0,0,to_date('15/07/30','RR/MM/DD'),to_date('15/07/30','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',21,'1','No pain No gain',null,0,0,0,to_date('15/07/30','RR/MM/DD'),to_date('15/07/30','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',22,'1','천만에요','My pleasure',0,0,0,to_date('15/07/30','RR/MM/DD'),to_date('15/07/30','RR/MM/DD'),'N','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('102',23,'1','It''s hard to say~',null,0,0,0,to_date('15/07/30','RR/MM/DD'),to_date('15/07/30','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',24,'1','d',null,0,0,0,to_date('15/07/30','RR/MM/DD'),to_date('15/07/30','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('102',25,'1','e',null,0,0,0,to_date('15/07/30','RR/MM/DD'),to_date('15/07/30','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',26,'1','헬스장 언제 갈래?',null,0,0,0,to_date('15/07/30','RR/MM/DD'),to_date('15/07/30','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('102',27,'1','Let''s chill out',null,0,0,1,to_date('15/07/30','RR/MM/DD'),to_date('15/07/30','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',28,'1','참 좋은 날이다',null,0,0,1,to_date('15/07/31','RR/MM/DD'),to_date('15/07/31','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',29,'5','아주 드물게',null,0,0,0,to_date('15/07/31','RR/MM/DD'),to_date('15/07/31','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',30,'5','영어에 관심이 없어용 :-(',null,0,0,0,to_date('15/07/31','RR/MM/DD'),to_date('15/07/31','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',31,'5','좋은 주말 보내세요',null,0,0,0,to_date('15/07/31','RR/MM/DD'),to_date('15/07/31','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',32,'5','시간 있으세요?(차 한잔 ok? )',null,0,0,1,to_date('15/07/31','RR/MM/DD'),to_date('15/07/31','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',33,'5','너 변비니?',null,0,0,0,to_date('15/07/31','RR/MM/DD'),to_date('15/07/31','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',34,'5','(전화에서)엄마 바꿔줄께',null,0,0,2,to_date('15/08/03','RR/MM/DD'),to_date('15/08/03','RR/MM/DD'),'Y','Y');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',35,'5','내가 뒤에서 도와줄께',null,0,0,1,to_date('15/08/03','RR/MM/DD'),to_date('15/08/03','RR/MM/DD'),'Y','Y');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',36,'5','(전화에서)잠깐만 기다려',null,0,0,1,to_date('15/08/03','RR/MM/DD'),to_date('15/08/03','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('103',37,'3','Hang up the phone',null,0,0,0,to_date('15/08/04','RR/MM/DD'),to_date('15/08/04','RR/MM/DD'),'Y','N');
Insert into PROENG.EN_BOARD (CODE_NO,SEQ_NO,ID,BOARD_TITLE,BOARD_CONTENT,BOARD_GROUP,BOARD_DEPTH,BOARD_HIT,BOARD_CRE_DATE,BOARD_MOD_DATE,IS_ATCH_FILE,IS_DELETE) values ('102',38,'3','What brought you here?',null,0,0,8,to_date('15/08/04','RR/MM/DD'),to_date('15/08/04','RR/MM/DD'),'Y','Y');
--------------------------------------------------------
--  DDL for Index PK_EN_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROENG"."PK_EN_BOARD" ON "PROENG"."EN_BOARD" ("SEQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EN_BOARD
--------------------------------------------------------

  ALTER TABLE "PROENG"."EN_BOARD" ADD CONSTRAINT "PK_EN_BOARD" PRIMARY KEY ("SEQ_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROENG"."EN_BOARD" MODIFY ("BOARD_CRE_DATE" NOT NULL ENABLE);
  ALTER TABLE "PROENG"."EN_BOARD" MODIFY ("BOARD_HIT" NOT NULL ENABLE);
  ALTER TABLE "PROENG"."EN_BOARD" MODIFY ("BOARD_TITLE" NOT NULL ENABLE);
  ALTER TABLE "PROENG"."EN_BOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROENG"."EN_BOARD" MODIFY ("SEQ_NO" NOT NULL ENABLE);
  ALTER TABLE "PROENG"."EN_BOARD" MODIFY ("CODE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EN_BOARD
--------------------------------------------------------

  ALTER TABLE "PROENG"."EN_BOARD" ADD CONSTRAINT "FK_EN_MEMBER_TO_EN_BOARD" FOREIGN KEY ("ID")
	  REFERENCES "PROENG"."EN_MEMBER" ("ID") ENABLE;
